on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

name: Markdown-to-Confluence
jobs:
  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Github Auth
        shell: bash
        env:
          XIA_MACHINE_SSH_KEY: ${{ secrets.XIA_MACHINE_SSH_KEY }}
        run: |
          mkdir ~/.ssh
          echo $XIA_MACHINE_SSH_KEY | base64 --decode >> ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: Unit tests
        run: make test

  lint:
    name: Lint code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Github Auth
        shell: bash
        env:
          XIA_MACHINE_SSH_KEY: ${{ secrets.XIA_MACHINE_SSH_KEY }}
        run: |
          mkdir ~/.ssh
          echo $XIA_MACHINE_SSH_KEY | base64 --decode >> ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global url."ssh://git@github.com/".insteadOf "https://github.com/"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.35.2
